server:
  port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/oauth2/jwks
logging:
  level:
    root: TRACE
    org.springframework.web: DEBUG
    com.dailycodebuffer.Oauthresourceserver: DEBUG