server:
  port: 9000

spring:
  application:
    name: auth-server
  security:
#    oauth2:
#      authorizationserver:
#        issuer: http://localhost:9000
#        client:
#          articles-client:
#            registration:
#              client-id: articles-client
#              client-secret: "secret"
#              client-name: Articles Client
#              client-authentication-methods:
#                - client_secret_basic
#              authorization-grant-types:
#                - authorization_code
#                - refresh_token
#              redirect-uris:
#                - http://127.0.0.1:9000/login/oauth2/code/articles-client
#                - http://127.0.0.1:9000/authorized
#              scopes:
#                - openid
#                - articles.read
    user:
      name: "admin"
      password: "password"

  liquibase:
    enabled: false

logging:
  level:
    root: TRACE
    org.springframework.web: DEBUG
    com.dailycodebuffer.oauthserver: DEBUG
